name: CD - DEPLOY

on:
  workflow_run:
    workflows: [ "CI - BUILD" ]
    types: [ completed ]
    branches: [ main, develop ]

concurrency:
  group: cd-deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_VERSION: 8.0.x
  DOCKER_IMAGE: ${{vars.DOCKERHUB_USERNAME}}/auth-system

jobs:
  check-ci:
    name: Check CI status
    runs-on: ubuntu-22.04
    outputs:
      should-deploy: ${{ steps.check.outputs.result }}
      branch: ${{ steps.branch.outputs.name }}
    steps:
      - name: Check CI result
        id: check
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then 
            echo "result=false" >> $GITHUB_OUTPUT
            echo "CI build failed. Skipping deployment."
          else
            echo "result=true" >> $GITHUB_OUTPUT
          fi

      - name: Get branch name
        id: branch
        run: echo "name = ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
  
  build-and-publish:
    name: Build and push Docker image
    runs-on: ubuntu-22.04
    needs: check-ci
    if: needs.check-ci.outputs.should-deploy == 'true'
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      sha_tag: ${{ steps.sha_tag.outputs.tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,prefix=,format=short
            type=ref,event=branch
            type=raw,value=latest,enable=${{github.event.workflow_run.head_branch == 'main'  }}
            type=raw,value=staging,enable=${{github.event.workflow_run.head_branch == 'develop'  }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Api
          push: true
          tags: ${{ steps.meta.outputs.tags}}
          labels: ${{ steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
    
    